# Kafka Settings
kafka.bootstrap.servers=127.0.0.1:9092
kafka.topic.input=word-input
kafka.group.id=storm-wordcount-group

# Topology Settings
topology.parallelism.spout=2
topology.parallelism.splitter=4
topology.parallelism.counter=2
topology.parallelism.alerter=2